export const PRODUCTS_LIST_REQUEST_PROCESSING = 'PRODUCTS_LIST_REQUEST_PROCESSING'
export const PRODUCTS_LIST_REQUEST_SUCCESSFUL = 'PRODUCTS_LIST_REQUEST_SUCCESSFUL'
export const PRODUCTS_LIST_REQUEST_FAIL = 'PRODUCTS_LIST_REQUEST_FAIL'
export const PRODUCT_DETAILS_REQUEST_PROCESSING = 'PRODUCT_DETAILS_REQUEST_PROCESSING'
export const PRODUCT_DETAILS_REQUEST_SUCCESSFUL = 'PRODUCT_DETAILS_REQUEST_SUCCESSFUL'
export const PRODUCT_DETAILS_REQUEST_FAIL = 'PRODUCT_DETAILS_REQUEST_FAIL'

export const ADD_ITEM_TO_CART_REQUEST_PROCESSING = 'ADD_ITEM_TO_CART_REQUEST_PROCESSING'
export const ADD_ITEM_TO_CART_REQUEST_SUCCESS = 'ADD_ITEM_TO_CART_REQUEST_SUCCESS'
export const ADD_ITEM_TO_CART_FAIL = 'ADD_ITEM_TO_CART_FAIL'

export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART'

export const USER_LOGIN_REQUEST_PROCESSING = 'USER_LOGIN_REQUEST_PROCESSING'
export const USER_LOGIN_REQUEST_SUCCESSFUL = 'USER_LOGIN_REQUEST_SUCCESSFUL'
export const USER_LOGIN_REQUEST_FAIL = 'USER_LOGIN_REQUEST_FAIL'

export const USER_REGISTER_REQUEST_PROCESSING = 'USER_REGISTER_REQUEST_PROCESSING'
export const USER_REGISTER_REQUEST_SUCCESSFUL = 'USER_REGISTER_REQUEST_SUCCESSFUL'
export const USER_REGISTER_REQUEST_FAIL = 'USER_REGISTER_REQUEST_FAIL'

export const CREATE_PRODUCT_REQUEST_PROCESSING = 'CREATE_PRODUCT_REQUEST_PROCESSING'
export const CREATE_PRODUCT_REQUEST_SUCCESSFUL = 'CREATE_PRODUCT_REQUEST_SUCCESSFUL'
export const CREATE_PRODUCT_REQUEST_FAIL = 'CREATE_PRODUCT_REQUEST_FAIL'

export const EDIT_PRODUCT_REQUEST_PROCESSING = 'EDIT_PRODUCT_REQUEST_PROCESSING'
export const EDIT_PRODUCT_REQUEST_SUCCESSFUL = 'EDIT_PRODUCT_REQUEST_SUCCESSFUL'
export const EDIT_PRODUCT_REQUEST_FAIL  = 'EDIT_PRODUCT_REQUEST_FAIL'

export const DELETE_PRODUCT_REQUEST_PROCESSING = 'DELETE_PRODUCT_REQUEST_PROCESSING'
export const DELETE_PRODUCT_REQUEST_SUCCESSFUL = 'DELETE_PRODUCT_REQUEST_SUCCESSFUL'
export const DELETE_PRODUCT_REQUEST_FAIL = 'DELETE_PRODUCT_REQUEST_FAIL'

export const SAVE_DELIVERY_DETAILS = 'SAVE_DELIVERY_DETAILS'
export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD'

export const ORDER_CREATE_REQUEST_PROCESSING = 'ORDER_CREATE_REQUEST_PROCESSING'
export const ORDER_CREATE_REQUEST_SUCCESS = 'ORDER_CREATE_REQUEST_SUCCESS'
export const ORDER_CREATE_REQUEST_FAIL = 'ORDER_CREATE_REQUEST_FAIL'

export const DELETE_CART = 'DELETE_CART'

export const GET_MY_ORDERS_REQUEST_PROCESSING = 'GET_MY_ORDERS_REQUEST_PROCESSING'
export const GET_MY_ORDERS_REQUEST_SUCCESS = 'GET_MY_ORDERS_REQUEST_SUCCESS'
export const GET_MY_ORDERS_REQUEST_FAIL = 'GET_MY_ORDERS_REQUEST_FAIL'

export const GET_ORDER_DETAILS_REQUEST_PROCESSING = 'GET_ORDER_DETAILS_REQUEST_PROCESSING'
export const GET_ORDER_DETAILS_REQUEST_SUCCESS = 'GET_ORDER_DETAILS_REQUEST_SUCCESS'
export const GET_ORDER_DETAILS_REQUEST_FAIL = 'GET_ORDER_DETAILS_REQUEST_FAIL'


export const SET_ADD_TO_CART_ERROR = 'SET_ADD_TO_CART_ERROR'
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR'
export const SET_REGISTER_ERROR = 'SET_REGISTER_ERROR'
export const SET_LOGOUT_ERROR = 'SET_LOGOUT_ERROR'
export const SET_CREATE_ORDER_ERROR = 'SET_CREATE_ORDER_ERROR'

export const GET_ALL_ORDERS_REQUEST_PROCESSING = 'GET_ALL_ORDERS_REQUEST_PROCESSING'
export const GET_ALL_ORDERS_REQUEST_SUCCESS = 'GET_ALL_ORDERS_REQUEST_SUCCESS'
export const GET_ALL_ORDERS_REQUEST_FAIL = 'GET_ALL_ORDERS_REQUEST_FAIL'






export const LOGOUT = 'LOGOUT'


export const NEXT_STEP = 'NEXT_STEP'
export const PREVIOUS_STEP = 'PREVIOUS_STEP'




































